
import DashboardProfile from "@/components/profile_component/DashboardProfile";
import Profile from "@/components/profile_component/Profile";
import CommonPageTitle from "@/components/ui/CommonPageTitle";
import { Button } from "antd";
import { Metadata } from "next";
import Link from "next/link";


export const metadata: Metadata = {
    title: "Profile - HomeSync Solution",
    description: 'Generated by create next app',
}


export default function UserDashboardHome() {
    return (
        <>
            <DashboardProfile />
        </>
    )
}
