
import Providers from '@/lib/Providers'
import './globals.css'

import Navbar from '@/components/shared/Navbar'
import { getFromLocalStorage } from '@/utils/local-storage'

import { authKey } from '@/constants/storageKey'
import { useEffect } from 'react'
import { useAppDispatch } from '@/redux/hook'
import { fetchUser } from '@/redux/slices/userSlice'
import { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // const dispatch = useAppDispatch()
  // const token = getFromLocalStorage(authKey)
  // useEffect(() => {
  //   dispatch(fetchUser(token as string))
  // }, [token])
  return (
    <Providers>
      <html lang="en">
        <body>{children}</body>
      </html>
    </Providers>

  )
}
