
import Providers from '@/lib/Providers'
import './globals.css'

import Navbar from '@/components/shared/Navbar'
import { AntdRegistry } from '@ant-design/nextjs-registry'


// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Providers>
      <html lang="en">
        <body>
          <AntdRegistry>
            {/* <Navbar /> */}
            {children}
          </AntdRegistry>
        </body>
      </html>
    </Providers>

  )
}
