import Banner from "@/components/home_component/Banner";
import PageLayout from "@/components/layout/PageLayout";
import RecentServices from '@/components/home_component/RecentServices';
import WhyChooseUs from '@/components/home_component/WhyChooseUs';
import TopCategories from '@/components/home_component/TopCategories';
import RecentClientReviews from "@/components/home_component/RecentClientReviews";
import TotalCalculation from "@/components/home_component/TotalCalculation";
import HowItWorks from "@/components/home_component/HowItWorks";
import { Metadata } from "next";
import FaqSection from "@/components/shared/FaqSection";



export const metadata: Metadata = {
  title: 'Home - HomeSync Solution',
  description: 'Generated by create next app',
}



export default function Home() {
  return (
    <PageLayout>
      <Banner />
      <RecentServices />
      <TopCategories />
      <RecentClientReviews />
      <TotalCalculation />
      <WhyChooseUs />
      <HowItWorks />
      <FaqSection />
    </PageLayout>
  )
}
