

export const metadata = {
  title: 'Profile -HomeSync Solution',
  description: 'Generated by create next app',
}


import PageLayout from "@/components/layout/PageLayout"
import Profile from "@/components/profile_component/Profile"


export default function page() {

  return (
    <PageLayout>
      <Profile />
    </PageLayout>
  )
}
